---
# tasks file for webserver

- name : "Installing Server"
  package :
    name : httpd
    state : present

- name : "Creating Desired Document Root in Target..."
  file : 
    state : directory
    dest : "{{dr}}"


- name : "Copying Configuration File...."
  template :
    dest : /etc/httpd/conf.d/web.conf
    src : web.conf.j2 
  notify : "restart"

- name : "Transfering Website"
  template : 
    dest : "{{dr}}/index.html"
    src : index.html.j2

- name : "Start Service.."
  service :
    name : httpd
    state : started
