---
# tasks file for myloadbalancer

- name : Installing haproxy
  package : 
    name : haproxy
    state : present      

- name : Sending conf file
  template :
    src : "haproxy.cfg.j2"
    dest : /etc/haproxy/haproxy.cfg
  notify : restart

- name : Start the service
  service :
    name : haproxy
    state : started




